[package]
name = "aplena"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "aplena_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
pfcm-domain = { path = "../crates/pfcm-domain" }
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
uuid.workspace = true
